# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django_user_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_user_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=512, upload_to=django_user_images.models.hash_upload, verbose_name=b'Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.IntegerField(blank=True, editable=False, verbose_name=b'File size in bytes'),
        ),
    ]
